#first we print the list of students
puts "The students of the September 2014 cohort at Makers Academy"

puts "-----------------------------------------------------------"
puts "Enrique Comba Riepenhausen"
puts "Stephen Llolyd"
puts "Alex Peattle"
puts "Vic 329"
puts "Nicole Pell"
puts "Bernard"
puts "Elena Garrone"
puts "Yvette Cook"
puts "Stephen Giles"
puts "Ana Isabel Nogal"
puts "Craigh 44"
puts "Tim Scully"
puts "Ella Schofield"
puts "Fadie H"
puts "Mala 23"
puts "Zrasool88"
puts "Galicians"
puts "Dan Jocutler"
puts "Camilla Van Klinken"
puts "Sandrine"
puts "James Ascarter"
puts "Sl Stevens"
puts "Schlap"
puts "Andrew Hercules"
puts "Karine Nielsen"
puts "Andrew Snead"
puts "Rachel Nolan"
puts "Galalag"
puts "Anna Schechter"
puts "Alex Fakhri"
puts "Denise"
puts "Andrew Harrison"
#finally, we print the total
print "Overall, we have "
#it's important that print() doesn't add new line characters
print 32
puts " phenomenal students!"